# Generated by Django 5.1.2 on 2024-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='approval_request_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
