# Generated by Django 5.1.2 on 2024-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
